Levels:
 MaxLevel: 40
 Equation: "%level%*2+3^(%level%+2)"
Default:
 UseMySql: false
 MySqlIP: 0.0.0.0
 MySqlLogin: root
 MySqlPass: ""
 MySqlDatabase: "main"
 MySqlPort: 0
ItemAtributes:
 UseArmor: true
 UseArmorPenetration: true
 UseCrit: true
 UseDamage: true
 UseDodge: true
 UseHealth: true
 UseLifSteal: true
 
 